import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'hampter.freezed.dart';

@freezed
class Hampter with _$Hampter {
  const factory Hampter({
    required String name,
    required String description,
  }) = _Hampter;
}
